// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model

import kotlin.Int
import kotlin.Long
import kotlin.String

/**
 * Class ImageInfo.
 */
data class ImageInfo(
	val imageType: ImageType,
	/**
	 * Gets or sets the index of the image.
	 */
	val imageIndex: Int? = null,
	/**
	 * Gets or sets the image tag.
	 */
	val imageTag: String? = null,
	/**
	 * Gets or sets the path.
	 */
	val path: String? = null,
	/**
	 * Gets or sets the blurhash.
	 */
	val blurHash: String? = null,
	/**
	 * Gets or sets the height.
	 */
	val height: Int? = null,
	/**
	 * Gets or sets the width.
	 */
	val width: Int? = null,
	/**
	 * Gets or sets the size.
	 */
	val size: Long
)
