// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model

import kotlin.Boolean
import kotlin.Double
import kotlin.Float
import kotlin.Int
import kotlin.String

/**
 * Class MediaStream.
 */
data class MediaStream(
	/**
	 * Gets or sets the codec.
	 */
	val codec: String? = null,
	/**
	 * Gets or sets the codec tag.
	 */
	val codecTag: String? = null,
	/**
	 * Gets or sets the language.
	 */
	val language: String? = null,
	/**
	 * Gets or sets the color range.
	 */
	val colorRange: String? = null,
	/**
	 * Gets or sets the color space.
	 */
	val colorSpace: String? = null,
	/**
	 * Gets or sets the color transfer.
	 */
	val colorTransfer: String? = null,
	/**
	 * Gets or sets the color primaries.
	 */
	val colorPrimaries: String? = null,
	/**
	 * Gets or sets the comment.
	 */
	val comment: String? = null,
	/**
	 * Gets or sets the time base.
	 */
	val timeBase: String? = null,
	/**
	 * Gets or sets the codec time base.
	 */
	val codecTimeBase: String? = null,
	/**
	 * Gets or sets the title.
	 */
	val title: String? = null,
	/**
	 * Gets or sets the video range.
	 */
	val videoRange: String? = null,
	val localizedUndefined: String? = null,
	val localizedDefault: String? = null,
	val localizedForced: String? = null,
	val displayTitle: String? = null,
	val nalLengthSize: String? = null,
	/**
	 * Gets or sets a value indicating whether this instance is interlaced.
	 */
	val isInterlaced: Boolean,
	val isAvc: Boolean? = null,
	/**
	 * Gets or sets the channel layout.
	 */
	val channelLayout: String? = null,
	/**
	 * Gets or sets the bit rate.
	 */
	val bitRate: Int? = null,
	/**
	 * Gets or sets the bit depth.
	 */
	val bitDepth: Int? = null,
	/**
	 * Gets or sets the reference frames.
	 */
	val refFrames: Int? = null,
	/**
	 * Gets or sets the length of the packet.
	 */
	val packetLength: Int? = null,
	/**
	 * Gets or sets the channels.
	 */
	val channels: Int? = null,
	/**
	 * Gets or sets the sample rate.
	 */
	val sampleRate: Int? = null,
	/**
	 * Gets or sets a value indicating whether this instance is default.
	 */
	val isDefault: Boolean,
	/**
	 * Gets or sets a value indicating whether this instance is forced.
	 */
	val isForced: Boolean,
	/**
	 * Gets or sets the height.
	 */
	val height: Int? = null,
	/**
	 * Gets or sets the width.
	 */
	val width: Int? = null,
	/**
	 * Gets or sets the average frame rate.
	 */
	val averageFrameRate: Float? = null,
	/**
	 * Gets or sets the real frame rate.
	 */
	val realFrameRate: Float? = null,
	/**
	 * Gets or sets the profile.
	 */
	val profile: String? = null,
	val type: MediaStreamType,
	/**
	 * Gets or sets the aspect ratio.
	 */
	val aspectRatio: String? = null,
	/**
	 * Gets or sets the index.
	 */
	val index: Int,
	/**
	 * Gets or sets the score.
	 */
	val score: Int? = null,
	/**
	 * Gets or sets a value indicating whether this instance is external.
	 */
	val isExternal: Boolean,
	val deliveryMethod: SubtitleDeliveryMethod,
	/**
	 * Gets or sets the delivery URL.
	 */
	val deliveryUrl: String? = null,
	/**
	 * Gets or sets a value indicating whether this instance is external URL.
	 */
	val isExternalUrl: Boolean? = null,
	val isTextSubtitleStream: Boolean,
	/**
	 * Gets or sets a value indicating whether [supports external stream].
	 */
	val supportsExternalStream: Boolean,
	/**
	 * Gets or sets the filename.
	 */
	val path: String? = null,
	/**
	 * Gets or sets the pixel format.
	 */
	val pixelFormat: String? = null,
	/**
	 * Gets or sets the level.
	 */
	val level: Double? = null,
	/**
	 * Gets a value indicating whether this instance is anamorphic.
	 */
	val isAnamorphic: Boolean? = null
)
