// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model

import kotlin.Long
import kotlin.String

data class PlaystateRequest(
	val command: PlaystateCommand,
	val seekPositionTicks: Long? = null,
	/**
	 * Gets or sets the controlling user identifier.
	 */
	val controllingUserId: String? = null
)
