// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model

import kotlin.Int
import kotlin.String
import kotlin.collections.List

/**
 * Class RemoteImageResult.
 */
data class RemoteImageResult(
	/**
	 * Gets or sets the images.
	 */
	val images: List<RemoteImageInfo>? = null,
	/**
	 * Gets or sets the total record count.
	 */
	val totalRecordCount: Int,
	/**
	 * Gets or sets the providers.
	 */
	val providers: List<String>? = null
)
