// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model

import kotlin.Boolean
import kotlin.String

/**
 * The update user password request body.
 */
data class UpdateUserPassword(
	/**
	 * Gets or sets the current sha1-hashed password.
	 */
	val currentPassword: String? = null,
	/**
	 * Gets or sets the current plain text password.
	 */
	val currentPw: String? = null,
	/**
	 * Gets or sets the new plain text password.
	 */
	val newPw: String? = null,
	/**
	 * Gets or sets a value indicating whether to reset the password.
	 */
	val resetPassword: Boolean
)
