package org.jellyfin.sdk.model.constant

// https://github.com/jellyfin/jellyfin/blob/v10.8.4/MediaBrowser.Model/Querying/ItemSortBy.cs
public object ItemSortBy {
	public const val AiredEpisodeOrder: String = "AiredEpisodeOrder"
	public const val Album: String = "Album"
	public const val AlbumArtist: String = "AlbumArtist"
	public const val Artist: String = "Artist"
	public const val DateCreated: String = "DateCreated"
	public const val OfficialRating: String = "OfficialRating"
	public const val DatePlayed: String = "DatePlayed"
	public const val PremiereDate: String = "PremiereDate"
	public const val StartDate: String = "StartDate"
	public const val SortName: String = "SortName"
	public const val Name: String = "Name"
	public const val Random: String = "Random"
	public const val Runtime: String = "Runtime"
	public const val CommunityRating: String = "CommunityRating"
	public const val ProductionYear: String = "ProductionYear"
	public const val PlayCount: String = "PlayCount"
	public const val CriticRating: String = "CriticRating"
	public const val IsFolder: String = "IsFolder"
	public const val IsUnplayed: String = "IsUnplayed"
	public const val IsPlayed: String = "IsPlayed"
	public const val SeriesSortName: String = "SeriesSortName"
	public const val VideoBitRate: String = "VideoBitRate"
	public const val AirTime: String = "AirTime"
	public const val Studio: String = "Studio"
	public const val IsFavoriteOrLiked: String = "IsFavoriteOrLiked"
	public const val DateLastContentAdded: String = "DateLastContentAdded"
	public const val SeriesDatePlayed: String = "SeriesDatePlayed"
	public const val ParentIndexNumber: String = "ParentIndexNumber"
	public const val IndexNumber: String = "IndexNumber"
	public const val SimilarityScore: String = "SimilarityScore"
}
