// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The admin notification dto.
 */
@Serializable
public data class AdminNotificationDto(
	/**
	 * The notification name.
	 */
	@SerialName("Name")
	public val name: String? = null,
	/**
	 * The notification description.
	 */
	@SerialName("Description")
	public val description: String? = null,
	/**
	 * The notification level.
	 */
	@SerialName("NotificationLevel")
	public val notificationLevel: NotificationLevel? = null,
	/**
	 * The notification url.
	 */
	@SerialName("Url")
	public val url: String? = null,
)
