// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An enum representing formats of spatial audio.
 */
@Serializable
public enum class AudioSpatialFormat(
	public val serialName: String,
) {
	@SerialName("None")
	NONE("None"),
	@SerialName("DolbyAtmos")
	DOLBY_ATMOS("DolbyAtmos"),
	@SerialName("DTSX")
	DTSX("DTSX"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): AudioSpatialFormat? = when (serialName) {
			"None" -> NONE
			"DolbyAtmos" -> DOLBY_ATMOS
			"DTSX" -> DTSX
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): AudioSpatialFormat =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
