// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Deprecated
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The authenticate user by name request body.
 */
@Serializable
public data class AuthenticateUserByName(
	/**
	 * Gets or sets the username.
	 */
	@SerialName("Username")
	public val username: String? = null,
	/**
	 * Gets or sets the plain text password.
	 */
	@SerialName("Pw")
	public val pw: String? = null,
	/**
	 * Gets or sets the sha1-hashed password.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("Password")
	public val password: String? = null
)
