// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(DateTimeSerializer::class)

package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.DateTime
import org.jellyfin.sdk.model.serializer.DateTimeSerializer

/**
 * Manifest type for backups internal structure.
 */
@Serializable
public data class BackupManifestDto(
	/**
	 * The jellyfin version this backup was created with.
	 */
	@SerialName("ServerVersion")
	public val serverVersion: String,
	/**
	 * The backup engine version this backup was created with.
	 */
	@SerialName("BackupEngineVersion")
	public val backupEngineVersion: String,
	/**
	 * The date this backup was created with.
	 */
	@SerialName("DateCreated")
	public val dateCreated: DateTime,
	/**
	 * The path to the backup on the system.
	 */
	@SerialName("Path")
	public val path: String,
	/**
	 * The contents of the backup archive.
	 */
	@SerialName("Options")
	public val options: BackupOptionsDto,
)
