// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The cast receiver application model.
 */
@Serializable
public data class CastReceiverApplication(
	/**
	 * The cast receiver application id.
	 */
	@SerialName("Id")
	public val id: String,
	/**
	 * The cast receiver application name.
	 */
	@SerialName("Name")
	public val name: String,
)
