// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enum ChannelType.
 */
@Serializable
public enum class ChannelType(
	public val serialName: String,
) {
	@SerialName("TV")
	TV("TV"),
	@SerialName("Radio")
	RADIO("Radio"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): ChannelType? = when (serialName) {
			"TV" -> TV
			"Radio" -> RADIO
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): ChannelType =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
