// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Boolean
import kotlin.Deprecated
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Client capabilities dto.
 */
@Serializable
public data class ClientCapabilitiesDto(
	/**
	 * The list of playable media types.
	 */
	@SerialName("PlayableMediaTypes")
	public val playableMediaTypes: List<MediaType>,
	/**
	 * The list of supported commands.
	 */
	@SerialName("SupportedCommands")
	public val supportedCommands: List<GeneralCommandType>,
	/**
	 * A value indicating whether session supports media control.
	 */
	@SerialName("SupportsMediaControl")
	public val supportsMediaControl: Boolean,
	/**
	 * A value indicating whether session supports a persistent identifier.
	 */
	@SerialName("SupportsPersistentIdentifier")
	public val supportsPersistentIdentifier: Boolean,
	/**
	 * The device profile.
	 */
	@SerialName("DeviceProfile")
	public val deviceProfile: DeviceProfile? = null,
	/**
	 * The app store url.
	 */
	@SerialName("AppStoreUrl")
	public val appStoreUrl: String? = null,
	/**
	 * The icon url.
	 */
	@SerialName("IconUrl")
	public val iconUrl: String? = null,
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("SupportsContentUploading")
	public val supportsContentUploading: Boolean? = false,
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("SupportsSync")
	public val supportsSync: Boolean? = false,
)
