// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ContainerProfile(
	@SerialName("Type")
	public val type: DlnaProfileType,
	@SerialName("Conditions")
	public val conditions: List<ProfileCondition>? = null,
	@SerialName("Container")
	public val container: String
)
