// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which
 * content a certain device is able to play.
 *
 *
 * Specifically, it defines the supported containers
 * (`P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles`) and
 * codecs (`P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles`) (video and/or audio, including
 * codec profiles and levels)
 * the device is able to direct play (without transcoding or remuxing),
 * as well as which containers/codecs to transcode to
 * (`P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles`) in case it isn't.
 */
@Serializable
public data class DeviceProfile(
	/**
	 * The name of this device profile.
	 */
	@SerialName("Name")
	public val name: String? = null,
	/**
	 * The Id.
	 */
	@SerialName("Id")
	public val id: String? = null,
	/**
	 * The Identification.
	 */
	@SerialName("Identification")
	public val identification: DeviceIdentification? = null,
	/**
	 * The friendly name of the device profile, which can be shown to users.
	 */
	@SerialName("FriendlyName")
	public val friendlyName: String? = null,
	/**
	 * The manufacturer of the device which this profile represents.
	 */
	@SerialName("Manufacturer")
	public val manufacturer: String? = null,
	/**
	 * An url for the manufacturer of the device which this profile represents.
	 */
	@SerialName("ManufacturerUrl")
	public val manufacturerUrl: String? = null,
	/**
	 * The model name of the device which this profile represents.
	 */
	@SerialName("ModelName")
	public val modelName: String? = null,
	/**
	 * The model description of the device which this profile represents.
	 */
	@SerialName("ModelDescription")
	public val modelDescription: String? = null,
	/**
	 * The model number of the device which this profile represents.
	 */
	@SerialName("ModelNumber")
	public val modelNumber: String? = null,
	/**
	 * The ModelUrl.
	 */
	@SerialName("ModelUrl")
	public val modelUrl: String? = null,
	/**
	 * The serial number of the device which this profile represents.
	 */
	@SerialName("SerialNumber")
	public val serialNumber: String? = null,
	/**
	 * A value indicating whether EnableAlbumArtInDidl.
	 */
	@SerialName("EnableAlbumArtInDidl")
	public val enableAlbumArtInDidl: Boolean = false,
	/**
	 * A value indicating whether EnableSingleAlbumArtLimit.
	 */
	@SerialName("EnableSingleAlbumArtLimit")
	public val enableSingleAlbumArtLimit: Boolean = false,
	/**
	 * A value indicating whether EnableSingleSubtitleLimit.
	 */
	@SerialName("EnableSingleSubtitleLimit")
	public val enableSingleSubtitleLimit: Boolean = false,
	/**
	 * The SupportedMediaTypes.
	 */
	@SerialName("SupportedMediaTypes")
	public val supportedMediaTypes: String,
	/**
	 * The UserId.
	 */
	@SerialName("UserId")
	public val userId: String? = null,
	/**
	 * The AlbumArtPn.
	 */
	@SerialName("AlbumArtPn")
	public val albumArtPn: String? = null,
	/**
	 * The MaxAlbumArtWidth.
	 */
	@SerialName("MaxAlbumArtWidth")
	public val maxAlbumArtWidth: Int? = null,
	/**
	 * The MaxAlbumArtHeight.
	 */
	@SerialName("MaxAlbumArtHeight")
	public val maxAlbumArtHeight: Int? = null,
	/**
	 * The maximum allowed width of embedded icons.
	 */
	@SerialName("MaxIconWidth")
	public val maxIconWidth: Int? = null,
	/**
	 * The maximum allowed height of embedded icons.
	 */
	@SerialName("MaxIconHeight")
	public val maxIconHeight: Int? = null,
	/**
	 * The maximum allowed bitrate for all streamed content.
	 */
	@SerialName("MaxStreamingBitrate")
	public val maxStreamingBitrate: Int? = null,
	/**
	 * The maximum allowed bitrate for statically streamed content (= direct played files).
	 */
	@SerialName("MaxStaticBitrate")
	public val maxStaticBitrate: Int? = null,
	/**
	 * The maximum allowed bitrate for transcoded music streams.
	 */
	@SerialName("MusicStreamingTranscodingBitrate")
	public val musicStreamingTranscodingBitrate: Int? = null,
	/**
	 * The maximum allowed bitrate for statically streamed (= direct played) music files.
	 */
	@SerialName("MaxStaticMusicBitrate")
	public val maxStaticMusicBitrate: Int? = null,
	/**
	 * The content of the aggregationFlags element in the urn:schemas-sonycom:av namespace.
	 */
	@SerialName("SonyAggregationFlags")
	public val sonyAggregationFlags: String? = null,
	/**
	 * The ProtocolInfo.
	 */
	@SerialName("ProtocolInfo")
	public val protocolInfo: String? = null,
	/**
	 * The TimelineOffsetSeconds.
	 */
	@SerialName("TimelineOffsetSeconds")
	public val timelineOffsetSeconds: Int = 0,
	/**
	 * A value indicating whether RequiresPlainVideoItems.
	 */
	@SerialName("RequiresPlainVideoItems")
	public val requiresPlainVideoItems: Boolean = false,
	/**
	 * A value indicating whether RequiresPlainFolders.
	 */
	@SerialName("RequiresPlainFolders")
	public val requiresPlainFolders: Boolean = false,
	/**
	 * A value indicating whether EnableMSMediaReceiverRegistrar.
	 */
	@SerialName("EnableMSMediaReceiverRegistrar")
	public val enableMsMediaReceiverRegistrar: Boolean = false,
	/**
	 * A value indicating whether IgnoreTranscodeByteRangeRequests.
	 */
	@SerialName("IgnoreTranscodeByteRangeRequests")
	public val ignoreTranscodeByteRangeRequests: Boolean = false,
	/**
	 * The XmlRootAttributes.
	 */
	@SerialName("XmlRootAttributes")
	public val xmlRootAttributes: List<XmlAttribute>,
	/**
	 * The direct play profiles.
	 */
	@SerialName("DirectPlayProfiles")
	public val directPlayProfiles: List<DirectPlayProfile>,
	/**
	 * The transcoding profiles.
	 */
	@SerialName("TranscodingProfiles")
	public val transcodingProfiles: List<TranscodingProfile>,
	/**
	 * The container profiles.
	 */
	@SerialName("ContainerProfiles")
	public val containerProfiles: List<ContainerProfile>,
	/**
	 * The codec profiles.
	 */
	@SerialName("CodecProfiles")
	public val codecProfiles: List<CodecProfile>,
	/**
	 * The ResponseProfiles.
	 */
	@SerialName("ResponseProfiles")
	public val responseProfiles: List<ResponseProfile>,
	/**
	 * The subtitle profiles.
	 */
	@SerialName("SubtitleProfiles")
	public val subtitleProfiles: List<SubtitleProfile>,
)
