// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Defines the MediaBrowser.Model.Dlna.DirectPlayProfile.
 */
@Serializable
public data class DirectPlayProfile(
	/**
	 * The container.
	 */
	@SerialName("Container")
	public val container: String,
	/**
	 * The audio codec.
	 */
	@SerialName("AudioCodec")
	public val audioCodec: String? = null,
	/**
	 * The video codec.
	 */
	@SerialName("VideoCodec")
	public val videoCodec: String? = null,
	/**
	 * The Dlna profile type.
	 */
	@SerialName("Type")
	public val type: DlnaProfileType,
)
