// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the external id information for serialization to the client.
 */
@Serializable
public data class ExternalIdInfo(
	/**
	 * Gets or sets the display name of the external id provider (IE: IMDB, MusicBrainz, etc).
	 */
	@SerialName("Name")
	public val name: String,
	/**
	 * Gets or sets the unique key for this id. This key should be unique across all providers.
	 */
	@SerialName("Key")
	public val key: String,
	/**
	 * Gets or sets the specific media type for this id. This is used to distinguish between the
	 * different
	 * external id types for providers with multiple ids.
	 * A null value indicates there is no specific media type associated with the external id, or this
	 * is the
	 * default id for the external provider so there is no need to specify a type.
	 */
	@SerialName("Type")
	public val type: ExternalIdMediaType? = null,
	/**
	 * Gets or sets the URL format string.
	 */
	@SerialName("UrlFormatString")
	public val urlFormatString: String
)
