// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.collections.Map
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.serializer.UUIDSerializer

@Serializable
public data class GeneralCommand(
	/**
	 * This exists simply to identify a set of known commands.
	 */
	@SerialName("Name")
	public val name: GeneralCommandType,
	@SerialName("ControllingUserId")
	public val controllingUserId: UUID,
	@SerialName("Arguments")
	public val arguments: Map<String, String?>,
)
