// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enum GroupUpdateType.
 */
@Serializable
public enum class GroupUpdateType(
	public val serialName: String,
) {
	@SerialName("UserJoined")
	USER_JOINED("UserJoined"),
	@SerialName("UserLeft")
	USER_LEFT("UserLeft"),
	@SerialName("GroupJoined")
	GROUP_JOINED("GroupJoined"),
	@SerialName("GroupLeft")
	GROUP_LEFT("GroupLeft"),
	@SerialName("StateUpdate")
	STATE_UPDATE("StateUpdate"),
	@SerialName("PlayQueue")
	PLAY_QUEUE("PlayQueue"),
	@SerialName("NotInGroup")
	NOT_IN_GROUP("NotInGroup"),
	@SerialName("GroupDoesNotExist")
	GROUP_DOES_NOT_EXIST("GroupDoesNotExist"),
	@SerialName("LibraryAccessDenied")
	LIBRARY_ACCESS_DENIED("LibraryAccessDenied"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): GroupUpdateType? = when (serialName) {
			"UserJoined" -> USER_JOINED
			"UserLeft" -> USER_LEFT
			"GroupJoined" -> GROUP_JOINED
			"GroupLeft" -> GROUP_LEFT
			"StateUpdate" -> STATE_UPDATE
			"PlayQueue" -> PLAY_QUEUE
			"NotInGroup" -> NOT_IN_GROUP
			"GroupDoesNotExist" -> GROUP_DOES_NOT_EXIST
			"LibraryAccessDenied" -> LIBRARY_ACCESS_DENIED
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): GroupUpdateType = requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
