// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ImageByNameInfo(
	/**
	 * Gets or sets the name.
	 */
	@SerialName("Name")
	public val name: String? = null,
	/**
	 * Gets or sets the theme.
	 */
	@SerialName("Theme")
	public val theme: String? = null,
	/**
	 * Gets or sets the context.
	 */
	@SerialName("Context")
	public val context: String? = null,
	/**
	 * Gets or sets the length of the file.
	 */
	@SerialName("FileLength")
	public val fileLength: Long,
	/**
	 * Gets or sets the format.
	 */
	@SerialName("Format")
	public val format: String? = null,
)
