// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Class ImageProviderInfo.
 */
@Serializable
public data class ImageProviderInfo(
	/**
	 * Gets the name.
	 */
	@SerialName("Name")
	public val name: String,
	/**
	 * Gets the supported image types.
	 */
	@SerialName("SupportedImages")
	public val supportedImages: List<ImageType>
)
