// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Class ImageInfo.
 */
@Serializable
public data class ImageInfo(
	/**
	 * The type of the image.
	 */
	@SerialName("ImageType")
	public val imageType: ImageType,
	/**
	 * The index of the image.
	 */
	@SerialName("ImageIndex")
	public val imageIndex: Int? = null,
	/**
	 * The image tag.
	 */
	@SerialName("ImageTag")
	public val imageTag: String? = null,
	/**
	 * The path.
	 */
	@SerialName("Path")
	public val path: String? = null,
	/**
	 * The blurhash.
	 */
	@SerialName("BlurHash")
	public val blurHash: String? = null,
	/**
	 * The height.
	 */
	@SerialName("Height")
	public val height: Int? = null,
	/**
	 * The width.
	 */
	@SerialName("Width")
	public val width: Int? = null,
	/**
	 * The size.
	 */
	@SerialName("Size")
	public val size: Long,
)
