// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Used to control the data that gets attached to DtoBaseItems.
 */
@Serializable
public enum class ItemFields(
	public val serialName: String,
) {
	@SerialName("AirTime")
	AIR_TIME("AirTime"),
	@SerialName("CanDelete")
	CAN_DELETE("CanDelete"),
	@SerialName("CanDownload")
	CAN_DOWNLOAD("CanDownload"),
	@SerialName("ChannelInfo")
	CHANNEL_INFO("ChannelInfo"),
	@SerialName("Chapters")
	CHAPTERS("Chapters"),
	@SerialName("Trickplay")
	TRICKPLAY("Trickplay"),
	@SerialName("ChildCount")
	CHILD_COUNT("ChildCount"),
	@SerialName("CumulativeRunTimeTicks")
	CUMULATIVE_RUN_TIME_TICKS("CumulativeRunTimeTicks"),
	@SerialName("CustomRating")
	CUSTOM_RATING("CustomRating"),
	@SerialName("DateCreated")
	DATE_CREATED("DateCreated"),
	@SerialName("DateLastMediaAdded")
	DATE_LAST_MEDIA_ADDED("DateLastMediaAdded"),
	@SerialName("DisplayPreferencesId")
	DISPLAY_PREFERENCES_ID("DisplayPreferencesId"),
	@SerialName("Etag")
	ETAG("Etag"),
	@SerialName("ExternalUrls")
	EXTERNAL_URLS("ExternalUrls"),
	@SerialName("Genres")
	GENRES("Genres"),
	@SerialName("HomePageUrl")
	HOME_PAGE_URL("HomePageUrl"),
	@SerialName("ItemCounts")
	ITEM_COUNTS("ItemCounts"),
	@SerialName("MediaSourceCount")
	MEDIA_SOURCE_COUNT("MediaSourceCount"),
	@SerialName("MediaSources")
	MEDIA_SOURCES("MediaSources"),
	@SerialName("OriginalTitle")
	ORIGINAL_TITLE("OriginalTitle"),
	@SerialName("Overview")
	OVERVIEW("Overview"),
	@SerialName("ParentId")
	PARENT_ID("ParentId"),
	@SerialName("Path")
	PATH("Path"),
	@SerialName("People")
	PEOPLE("People"),
	@SerialName("PlayAccess")
	PLAY_ACCESS("PlayAccess"),
	@SerialName("ProductionLocations")
	PRODUCTION_LOCATIONS("ProductionLocations"),
	@SerialName("ProviderIds")
	PROVIDER_IDS("ProviderIds"),
	@SerialName("PrimaryImageAspectRatio")
	PRIMARY_IMAGE_ASPECT_RATIO("PrimaryImageAspectRatio"),
	@SerialName("RecursiveItemCount")
	RECURSIVE_ITEM_COUNT("RecursiveItemCount"),
	@SerialName("Settings")
	SETTINGS("Settings"),
	@SerialName("ScreenshotImageTags")
	SCREENSHOT_IMAGE_TAGS("ScreenshotImageTags"),
	@SerialName("SeriesPrimaryImage")
	SERIES_PRIMARY_IMAGE("SeriesPrimaryImage"),
	@SerialName("SeriesStudio")
	SERIES_STUDIO("SeriesStudio"),
	@SerialName("SortName")
	SORT_NAME("SortName"),
	@SerialName("SpecialEpisodeNumbers")
	SPECIAL_EPISODE_NUMBERS("SpecialEpisodeNumbers"),
	@SerialName("Studios")
	STUDIOS("Studios"),
	@SerialName("Taglines")
	TAGLINES("Taglines"),
	@SerialName("Tags")
	TAGS("Tags"),
	@SerialName("RemoteTrailers")
	REMOTE_TRAILERS("RemoteTrailers"),
	@SerialName("MediaStreams")
	MEDIA_STREAMS("MediaStreams"),
	@SerialName("SeasonUserData")
	SEASON_USER_DATA("SeasonUserData"),
	@SerialName("ServiceName")
	SERVICE_NAME("ServiceName"),
	@SerialName("ThemeSongIds")
	THEME_SONG_IDS("ThemeSongIds"),
	@SerialName("ThemeVideoIds")
	THEME_VIDEO_IDS("ThemeVideoIds"),
	@SerialName("ExternalEtag")
	EXTERNAL_ETAG("ExternalEtag"),
	@SerialName("PresentationUniqueKey")
	PRESENTATION_UNIQUE_KEY("PresentationUniqueKey"),
	@SerialName("InheritedParentalRatingValue")
	INHERITED_PARENTAL_RATING_VALUE("InheritedParentalRatingValue"),
	@SerialName("ExternalSeriesId")
	EXTERNAL_SERIES_ID("ExternalSeriesId"),
	@SerialName("SeriesPresentationUniqueKey")
	SERIES_PRESENTATION_UNIQUE_KEY("SeriesPresentationUniqueKey"),
	@SerialName("DateLastRefreshed")
	DATE_LAST_REFRESHED("DateLastRefreshed"),
	@SerialName("DateLastSaved")
	DATE_LAST_SAVED("DateLastSaved"),
	@SerialName("RefreshState")
	REFRESH_STATE("RefreshState"),
	@SerialName("ChannelImage")
	CHANNEL_IMAGE("ChannelImage"),
	@SerialName("EnableMediaSourceDisplay")
	ENABLE_MEDIA_SOURCE_DISPLAY("EnableMediaSourceDisplay"),
	@SerialName("Width")
	WIDTH("Width"),
	@SerialName("Height")
	HEIGHT("Height"),
	@SerialName("ExtraIds")
	EXTRA_IDS("ExtraIds"),
	@SerialName("LocalTrailerCount")
	LOCAL_TRAILER_COUNT("LocalTrailerCount"),
	@SerialName("IsHD")
	IS_HD("IsHD"),
	@SerialName("SpecialFeatureCount")
	SPECIAL_FEATURE_COUNT("SpecialFeatureCount"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): ItemFields? = when (serialName) {
			"AirTime" -> AIR_TIME
			"CanDelete" -> CAN_DELETE
			"CanDownload" -> CAN_DOWNLOAD
			"ChannelInfo" -> CHANNEL_INFO
			"Chapters" -> CHAPTERS
			"Trickplay" -> TRICKPLAY
			"ChildCount" -> CHILD_COUNT
			"CumulativeRunTimeTicks" -> CUMULATIVE_RUN_TIME_TICKS
			"CustomRating" -> CUSTOM_RATING
			"DateCreated" -> DATE_CREATED
			"DateLastMediaAdded" -> DATE_LAST_MEDIA_ADDED
			"DisplayPreferencesId" -> DISPLAY_PREFERENCES_ID
			"Etag" -> ETAG
			"ExternalUrls" -> EXTERNAL_URLS
			"Genres" -> GENRES
			"HomePageUrl" -> HOME_PAGE_URL
			"ItemCounts" -> ITEM_COUNTS
			"MediaSourceCount" -> MEDIA_SOURCE_COUNT
			"MediaSources" -> MEDIA_SOURCES
			"OriginalTitle" -> ORIGINAL_TITLE
			"Overview" -> OVERVIEW
			"ParentId" -> PARENT_ID
			"Path" -> PATH
			"People" -> PEOPLE
			"PlayAccess" -> PLAY_ACCESS
			"ProductionLocations" -> PRODUCTION_LOCATIONS
			"ProviderIds" -> PROVIDER_IDS
			"PrimaryImageAspectRatio" -> PRIMARY_IMAGE_ASPECT_RATIO
			"RecursiveItemCount" -> RECURSIVE_ITEM_COUNT
			"Settings" -> SETTINGS
			"ScreenshotImageTags" -> SCREENSHOT_IMAGE_TAGS
			"SeriesPrimaryImage" -> SERIES_PRIMARY_IMAGE
			"SeriesStudio" -> SERIES_STUDIO
			"SortName" -> SORT_NAME
			"SpecialEpisodeNumbers" -> SPECIAL_EPISODE_NUMBERS
			"Studios" -> STUDIOS
			"Taglines" -> TAGLINES
			"Tags" -> TAGS
			"RemoteTrailers" -> REMOTE_TRAILERS
			"MediaStreams" -> MEDIA_STREAMS
			"SeasonUserData" -> SEASON_USER_DATA
			"ServiceName" -> SERVICE_NAME
			"ThemeSongIds" -> THEME_SONG_IDS
			"ThemeVideoIds" -> THEME_VIDEO_IDS
			"ExternalEtag" -> EXTERNAL_ETAG
			"PresentationUniqueKey" -> PRESENTATION_UNIQUE_KEY
			"InheritedParentalRatingValue" -> INHERITED_PARENTAL_RATING_VALUE
			"ExternalSeriesId" -> EXTERNAL_SERIES_ID
			"SeriesPresentationUniqueKey" -> SERIES_PRESENTATION_UNIQUE_KEY
			"DateLastRefreshed" -> DATE_LAST_REFRESHED
			"DateLastSaved" -> DATE_LAST_SAVED
			"RefreshState" -> REFRESH_STATE
			"ChannelImage" -> CHANNEL_IMAGE
			"EnableMediaSourceDisplay" -> ENABLE_MEDIA_SOURCE_DISPLAY
			"Width" -> WIDTH
			"Height" -> HEIGHT
			"ExtraIds" -> EXTRA_IDS
			"LocalTrailerCount" -> LOCAL_TRAILER_COUNT
			"IsHD" -> IS_HD
			"SpecialFeatureCount" -> SPECIAL_FEATURE_COUNT
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): ItemFields =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
