// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * LyricResponse model.
 */
@Serializable
public data class LyricDto(
	/**
	 * Metadata for the lyrics.
	 */
	@SerialName("Metadata")
	public val metadata: LyricMetadata,
	/**
	 * A collection of individual lyric lines.
	 */
	@SerialName("Lyrics")
	public val lyrics: List<LyricLine>,
)
