// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class PlayMethod(
	public val serialName: String,
) {
	@SerialName("Transcode")
	TRANSCODE("Transcode"),
	@SerialName("DirectStream")
	DIRECT_STREAM("DirectStream"),
	@SerialName("DirectPlay")
	DIRECT_PLAY("DirectPlay"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): PlayMethod? = when (serialName) {
			"Transcode" -> TRANSCODE
			"DirectStream" -> DIRECT_STREAM
			"DirectPlay" -> DIRECT_PLAY
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): PlayMethod =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
