// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class ProfileConditionType(
	public val serialName: String,
) {
	@SerialName("Equals")
	EQUALS("Equals"),
	@SerialName("NotEquals")
	NOT_EQUALS("NotEquals"),
	@SerialName("LessThanEqual")
	LESS_THAN_EQUAL("LessThanEqual"),
	@SerialName("GreaterThanEqual")
	GREATER_THAN_EQUAL("GreaterThanEqual"),
	@SerialName("EqualsAny")
	EQUALS_ANY("EqualsAny"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): ProfileConditionType? = when (serialName) {
			"Equals" -> EQUALS
			"NotEquals" -> NOT_EQUALS
			"LessThanEqual" -> LESS_THAN_EQUAL
			"GreaterThanEqual" -> GREATER_THAN_EQUAL
			"EqualsAny" -> EQUALS_ANY
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): ProfileConditionType = requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
