// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Boolean
import kotlin.Deprecated
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class PublicSystemInfo(
	/**
	 * The local address.
	 */
	@SerialName("LocalAddress")
	public val localAddress: String? = null,
	/**
	 * The name of the server.
	 */
	@SerialName("ServerName")
	public val serverName: String? = null,
	/**
	 * The server version.
	 */
	@SerialName("Version")
	public val version: String? = null,
	/**
	 * The product name. This is the AssemblyProduct name.
	 */
	@SerialName("ProductName")
	public val productName: String? = null,
	/**
	 * The operating system.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("OperatingSystem")
	public val operatingSystem: String? = null,
	/**
	 * The id.
	 */
	@SerialName("Id")
	public val id: String? = null,
	/**
	 * A value indicating whether the startup wizard is completed.
	 */
	@SerialName("StartupWizardCompleted")
	public val startupWizardCompleted: Boolean? = null,
)
