// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The remote lyric info dto.
 */
@Serializable
public data class RemoteLyricInfoDto(
	/**
	 * The id for the lyric.
	 */
	@SerialName("Id")
	public val id: String,
	/**
	 * The provider name.
	 */
	@SerialName("ProviderName")
	public val providerName: String,
	/**
	 * The lyrics.
	 */
	@SerialName("Lyrics")
	public val lyrics: LyricDto,
)
