// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(DateTimeSerializer::class)

package org.jellyfin.sdk.model.api

import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.DateTime
import org.jellyfin.sdk.model.serializer.DateTimeSerializer

@Serializable
public data class RemoteSubtitleInfo(
	@SerialName("ThreeLetterISOLanguageName")
	public val threeLetterIsoLanguageName: String? = null,
	@SerialName("Id")
	public val id: String? = null,
	@SerialName("ProviderName")
	public val providerName: String? = null,
	@SerialName("Name")
	public val name: String? = null,
	@SerialName("Format")
	public val format: String? = null,
	@SerialName("Author")
	public val author: String? = null,
	@SerialName("Comment")
	public val comment: String? = null,
	@SerialName("DateCreated")
	public val dateCreated: DateTime? = null,
	@SerialName("CommunityRating")
	public val communityRating: Float? = null,
	@SerialName("FrameRate")
	public val frameRate: Float? = null,
	@SerialName("DownloadCount")
	public val downloadCount: Int? = null,
	@SerialName("IsHashMatch")
	public val isHashMatch: Boolean? = null,
	@SerialName("AiTranslated")
	public val aiTranslated: Boolean? = null,
	@SerialName("MachineTranslated")
	public val machineTranslated: Boolean? = null,
	@SerialName("Forced")
	public val forced: Boolean? = null,
	@SerialName("HearingImpaired")
	public val hearingImpaired: Boolean? = null,
)
