// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(
	UUIDSerializer::class,
	DateTimeSerializer::class,
)

package org.jellyfin.sdk.model.api

import kotlin.Long
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.DateTime
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.serializer.DateTimeSerializer
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * Class SendCommand.
 */
@Serializable
public data class SendCommand(
	/**
	 * The group identifier.
	 */
	@SerialName("GroupId")
	public val groupId: UUID,
	/**
	 * The playlist identifier of the playing item.
	 */
	@SerialName("PlaylistItemId")
	public val playlistItemId: UUID,
	/**
	 * The UTC time when to execute the command.
	 */
	@SerialName("When")
	public val `when`: DateTime,
	/**
	 * The position ticks.
	 */
	@SerialName("PositionTicks")
	public val positionTicks: Long? = null,
	/**
	 * The command.
	 */
	@SerialName("Command")
	public val command: SendCommandType,
	/**
	 * The UTC time when this command has been emitted.
	 */
	@SerialName("EmittedAt")
	public val emittedAt: DateTime,
)
