// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An enum representing a subtitle playback mode.
 */
@Serializable
public enum class SubtitlePlaybackMode(
	public val serialName: String,
) {
	@SerialName("Default")
	DEFAULT("Default"),
	@SerialName("Always")
	ALWAYS("Always"),
	@SerialName("OnlyForced")
	ONLY_FORCED("OnlyForced"),
	@SerialName("None")
	NONE("None"),
	@SerialName("Smart")
	SMART("Smart"),
	;

	public override fun toString(): String = serialName

	public companion object {
		public fun fromNameOrNull(serialName: String): SubtitlePlaybackMode? = when (serialName) {
			"Default" -> DEFAULT
			"Always" -> ALWAYS
			"OnlyForced" -> ONLY_FORCED
			"None" -> NONE
			"Smart" -> SMART
			else -> null
		}

		public fun fromName(serialName: String): SubtitlePlaybackMode =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
