// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Defines the MediaBrowser.Model.Updates.VersionInfo class.
 */
@Serializable
public data class VersionInfo(
	/**
	 * The version.
	 */
	@SerialName("version")
	public val version: String,
	/**
	 * The version as a System.Version.
	 */
	@SerialName("VersionNumber")
	public val versionNumber: String,
	/**
	 * The changelog for this version.
	 */
	@SerialName("changelog")
	public val changelog: String? = null,
	/**
	 * The ABI that this version was built against.
	 */
	@SerialName("targetAbi")
	public val targetAbi: String? = null,
	/**
	 * The source URL.
	 */
	@SerialName("sourceUrl")
	public val sourceUrl: String? = null,
	/**
	 * A checksum for the binary.
	 */
	@SerialName("checksum")
	public val checksum: String? = null,
	/**
	 * A timestamp of when the binary was built.
	 */
	@SerialName("timestamp")
	public val timestamp: String? = null,
	/**
	 * The repository name.
	 */
	@SerialName("repositoryName")
	public val repositoryName: String,
	/**
	 * The repository url.
	 */
	@SerialName("repositoryUrl")
	public val repositoryUrl: String,
)
