// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.String
import kotlin.requireNotNull
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class Video3dFormat(
	public val serialName: String,
) {
	@SerialName("HalfSideBySide")
	HALF_SIDE_BY_SIDE("HalfSideBySide"),
	@SerialName("FullSideBySide")
	FULL_SIDE_BY_SIDE("FullSideBySide"),
	@SerialName("FullTopAndBottom")
	FULL_TOP_AND_BOTTOM("FullTopAndBottom"),
	@SerialName("HalfTopAndBottom")
	HALF_TOP_AND_BOTTOM("HalfTopAndBottom"),
	@SerialName("MVC")
	MVC("MVC"),
	;

	/**
	 * Get the serial name of the enum member.
	 */
	override fun toString(): String = serialName

	public companion object {
		/**
		 * Find the enum member by the serial name or return null.
		 */
		public fun fromNameOrNull(serialName: String): Video3dFormat? = when (serialName) {
			"HalfSideBySide" -> HALF_SIDE_BY_SIDE
			"FullSideBySide" -> FULL_SIDE_BY_SIDE
			"FullTopAndBottom" -> FULL_TOP_AND_BOTTOM
			"HalfTopAndBottom" -> HALF_TOP_AND_BOTTOM
			"MVC" -> MVC
			else -> null
		}

		/**
		 * Find the enum member by the serial name or throw.
		 */
		public fun fromName(serialName: String): Video3dFormat =
				requireNotNull(fromNameOrNull(serialName)) { """Unknown value $serialName""" }
	}
}
