// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

/**
 * Represents the possible websocket types
 */
public sealed interface WebSocketMessage {
	/**
	 * The different kinds of messages that are used in the WebSocket api.
	 */
	public val messageType: SessionMessageType
}
