// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(
	UUIDSerializer::class,
	LocalDateTimeSerializer::class
)

package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import java.util.UUID
import kotlin.Boolean
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.LocalDateTimeSerializer
import org.jellyfin.apiclient.model.serializer.UUIDSerializer

@Serializable
data class AuthenticationInfo(
	/**
	 * Gets or sets the identifier.
	 */
	@SerialName("Id")
	val id: Long,
	/**
	 * Gets or sets the access token.
	 */
	@SerialName("AccessToken")
	val accessToken: String? = null,
	/**
	 * Gets or sets the device identifier.
	 */
	@SerialName("DeviceId")
	val deviceId: String? = null,
	/**
	 * Gets or sets the name of the application.
	 */
	@SerialName("AppName")
	val appName: String? = null,
	/**
	 * Gets or sets the application version.
	 */
	@SerialName("AppVersion")
	val appVersion: String? = null,
	/**
	 * Gets or sets the name of the device.
	 */
	@SerialName("DeviceName")
	val deviceName: String? = null,
	/**
	 * Gets or sets the user identifier.
	 */
	@SerialName("UserId")
	val userId: UUID,
	/**
	 * Gets or sets a value indicating whether this instance is active.
	 */
	@SerialName("IsActive")
	val isActive: Boolean,
	/**
	 * Gets or sets the date created.
	 */
	@SerialName("DateCreated")
	val dateCreated: LocalDateTime,
	/**
	 * Gets or sets the date revoked.
	 */
	@SerialName("DateRevoked")
	val dateRevoked: LocalDateTime? = null,
	@SerialName("DateLastActivity")
	val dateLastActivity: LocalDateTime,
	@SerialName("UserName")
	val userName: String? = null
)
