// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.String
import kotlin.collections.Map

/**
 * This is used by the api to get information about a Person within a BaseItem.
 */
data class BaseItemPerson(
	/**
	 * Gets or sets the name.
	 */
	val name: String? = null,
	/**
	 * Gets or sets the identifier.
	 */
	val id: String? = null,
	/**
	 * Gets or sets the role.
	 */
	val role: String? = null,
	/**
	 * Gets or sets the type.
	 */
	val type: String? = null,
	/**
	 * Gets or sets the primary image tag.
	 */
	val primaryImageTag: String? = null,
	/**
	 * Gets or sets the primary image blurhash.
	 */
	val imageBlurHashes: Map<ImageType, Map<String, String>>
)
