// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

enum class ChannelMediaContentType {
	CLIP,

	PODCAST,

	TRAILER,

	MOVIE,

	EPISODE,

	SONG,

	MOVIE_EXTRA,

	TV_EXTRA
}
