// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(LocalDateTimeSerializer::class)

package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.LocalDateTimeSerializer

/**
 * Class ChapterInfo.
 */
@Serializable
data class ChapterInfo(
	/**
	 * Gets or sets the start position ticks.
	 */
	@SerialName("StartPositionTicks")
	val startPositionTicks: Long,
	/**
	 * Gets or sets the name.
	 */
	@SerialName("Name")
	val name: String? = null,
	/**
	 * Gets or sets the image path.
	 */
	@SerialName("ImagePath")
	val imagePath: String? = null,
	@SerialName("ImageDateModified")
	val imageDateModified: LocalDateTime,
	@SerialName("ImageTag")
	val imageTag: String? = null
)
