// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import java.util.UUID
import kotlin.String

data class DeviceInfo(
	val name: String? = null,
	/**
	 * Gets or sets the identifier.
	 */
	val id: String? = null,
	/**
	 * Gets or sets the last name of the user.
	 */
	val lastUserName: String? = null,
	/**
	 * Gets or sets the name of the application.
	 */
	val appName: String? = null,
	/**
	 * Gets or sets the application version.
	 */
	val appVersion: String? = null,
	/**
	 * Gets or sets the last user identifier.
	 */
	val lastUserId: UUID,
	/**
	 * Gets or sets the date last modified.
	 */
	val dateLastActivity: LocalDateTime,
	val capabilities: ClientCapabilities,
	val iconUrl: String? = null
)
