// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import kotlin.String

data class ForgotPasswordResult(
	val action: ForgotPasswordAction,
	/**
	 * Gets or sets the pin file.
	 */
	val pinFile: String? = null,
	/**
	 * Gets or sets the pin expiration date.
	 */
	val pinExpirationDate: LocalDateTime? = null
)
