// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.Double
import kotlin.String
import kotlin.collections.List

/**
 * Interface IScheduledTaskWorker.
 */
data class IScheduledTaskWorker(
	val scheduledTask: IScheduledTask,
	val lastExecutionResult: TaskResult,
	/**
	 * Gets the name.
	 */
	val name: String? = null,
	/**
	 * Gets the description.
	 */
	val description: String? = null,
	/**
	 * Gets the category.
	 */
	val category: String? = null,
	val state: TaskState,
	/**
	 * Gets the current progress.
	 */
	val currentProgress: Double? = null,
	/**
	 * Gets the triggers that define when the task will run.
	 */
	val triggers: List<TaskTriggerInfo>? = null,
	/**
	 * Gets the unique id.
	 */
	val id: String? = null
)
