// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Media Encoder Path Dto.
 */
@Serializable
data class MediaEncoderPathDto(
	/**
	 * Gets or sets media encoder path.
	 */
	@SerialName("Path")
	val path: String? = null,
	/**
	 * Gets or sets media encoder path type.
	 */
	@SerialName("PathType")
	val pathType: String? = null
)
