// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Media Path dto.
 */
@Serializable
data class MediaPathDto(
	/**
	 * Gets or sets the name of the library.
	 */
	@SerialName("Name")
	val name: String,
	/**
	 * Gets or sets the path to add.
	 */
	@SerialName("Path")
	val path: String? = null,
	@SerialName("PathInfo")
	val pathInfo: MediaPathInfo? = null
)
