// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.Boolean
import kotlin.String

/**
 * This is a serializable stub class that is used by the api to provide information about installed
 * plugins.
 */
data class PluginInfo(
	/**
	 * Gets or sets the name.
	 */
	val name: String? = null,
	/**
	 * Gets or sets the version.
	 */
	val version: String? = null,
	/**
	 * Gets or sets the name of the configuration file.
	 */
	val configurationFileName: String? = null,
	/**
	 * Gets or sets the description.
	 */
	val description: String? = null,
	/**
	 * Gets or sets the unique id.
	 */
	val id: String? = null,
	/**
	 * Gets or sets a value indicating whether the plugin can be uninstalled.
	 */
	val canUninstall: Boolean,
	/**
	 * Gets or sets the image URL.
	 */
	val imageUrl: String? = null
)
