// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(LocalDateTimeSerializer::class)

package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.LocalDateTimeSerializer

/**
 * Stores the result of an incoming quick connect request.
 */
@Serializable
data class QuickConnectResult(
	/**
	 * Gets a value indicating whether this request is authorized.
	 */
	@SerialName("Authenticated")
	val authenticated: Boolean,
	/**
	 * Gets or sets the secret value used to uniquely identify this request. Can be used to retrieve
	 * authentication information.
	 */
	@SerialName("Secret")
	val secret: String? = null,
	/**
	 * Gets or sets the user facing code used so the user can quickly differentiate this request from
	 * others.
	 */
	@SerialName("Code")
	val code: String? = null,
	/**
	 * Gets or sets the private access token.
	 */
	@SerialName("Authentication")
	val authentication: String? = null,
	/**
	 * Gets or sets an error message.
	 */
	@SerialName("Error")
	val error: String? = null,
	/**
	 * Gets or sets the DateTime that this request was created.
	 */
	@SerialName("DateAdded")
	val dateAdded: LocalDateTime? = null
)
