// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.String

data class RemoteSubtitleInfo(
	val threeLetterIsoLanguageName: String? = null,
	val id: String? = null,
	val providerName: String? = null,
	val name: String? = null,
	val format: String? = null,
	val author: String? = null,
	val comment: String? = null,
	val dateCreated: LocalDateTime? = null,
	val communityRating: Float? = null,
	val downloadCount: Int? = null,
	val isHashMatch: Boolean? = null
)
