// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.String

/**
 * Class RepositoryInfo.
 */
data class RepositoryInfo(
	/**
	 * Gets or sets the name.
	 */
	val name: String? = null,
	/**
	 * Gets or sets the URL.
	 */
	val url: String? = null
)
