// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.String
import kotlin.collections.List

data class ResponseProfile(
	val container: String? = null,
	val audioCodec: String? = null,
	val videoCodec: String? = null,
	val type: DlnaProfileType,
	val orgPn: String? = null,
	val mimeType: String? = null,
	val conditions: List<ProfileCondition>? = null
)
