// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.Int
import kotlin.collections.List

/**
 * Class SearchHintResult.
 */
data class SearchHintResult(
	/**
	 * Gets or sets the search hints.
	 */
	val searchHints: List<SearchHint>? = null,
	/**
	 * Gets or sets the total record count.
	 */
	val totalRecordCount: Int
)
