// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Class SendCommand.
 */
@Serializable
data class SendCommand(
	/**
	 * Gets or sets the group identifier.
	 */
	@SerialName("GroupId")
	val groupId: String? = null,
	/**
	 * Gets or sets the UTC time when to execute the command.
	 */
	@SerialName("When")
	val `when`: String? = null,
	/**
	 * Gets or sets the position ticks.
	 */
	@SerialName("PositionTicks")
	val positionTicks: Long? = null,
	@SerialName("Command")
	val command: SendCommandType? = null,
	/**
	 * Gets or sets the UTC time when this command has been emitted.
	 */
	@SerialName("EmittedAt")
	val emittedAt: String? = null
)
