// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enum GroupUpdateType.
 */
@Serializable
public enum class GroupUpdateType {
	@SerialName("UserJoined")
	USER_JOINED,
	@SerialName("UserLeft")
	USER_LEFT,
	@SerialName("GroupJoined")
	GROUP_JOINED,
	@SerialName("GroupLeft")
	GROUP_LEFT,
	@SerialName("StateUpdate")
	STATE_UPDATE,
	@SerialName("PlayQueue")
	PLAY_QUEUE,
	@SerialName("NotInGroup")
	NOT_IN_GROUP,
	@SerialName("GroupDoesNotExist")
	GROUP_DOES_NOT_EXIST,
	@SerialName("CreateGroupDenied")
	CREATE_GROUP_DENIED,
	@SerialName("JoinGroupDenied")
	JOIN_GROUP_DENIED,
	@SerialName("LibraryAccessDenied")
	LIBRARY_ACCESS_DENIED,
}
