// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enum ImageType.
 */
@Serializable
public enum class ImageType {
	@SerialName("Primary")
	PRIMARY,
	@SerialName("Art")
	ART,
	@SerialName("Backdrop")
	BACKDROP,
	@SerialName("Banner")
	BANNER,
	@SerialName("Logo")
	LOGO,
	@SerialName("Thumb")
	THUMB,
	@SerialName("Disc")
	DISC,
	@SerialName("Box")
	BOX,
	@SerialName("Screenshot")
	SCREENSHOT,
	@SerialName("Menu")
	MENU,
	@SerialName("Chapter")
	CHAPTER,
	@SerialName("BoxRear")
	BOX_REAR,
	@SerialName("Profile")
	PROFILE,
}
