// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(
	UUIDSerializer::class,
	LocalDateTimeSerializer::class
)

package org.jellyfin.sdk.model.api

import java.time.LocalDateTime
import java.util.UUID
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer
import org.jellyfin.sdk.model.serializer.UUIDSerializer

@Serializable
public data class TimerInfoDto(
	/**
	 * Id of the recording.
	 */
	@SerialName("Id")
	public val id: String? = null,
	@SerialName("Type")
	public val type: String? = null,
	/**
	 * Gets or sets the server identifier.
	 */
	@SerialName("ServerId")
	public val serverId: String? = null,
	/**
	 * Gets or sets the external identifier.
	 */
	@SerialName("ExternalId")
	public val externalId: String? = null,
	/**
	 * ChannelId of the recording.
	 */
	@SerialName("ChannelId")
	public val channelId: UUID,
	/**
	 * Gets or sets the external channel identifier.
	 */
	@SerialName("ExternalChannelId")
	public val externalChannelId: String? = null,
	/**
	 * ChannelName of the recording.
	 */
	@SerialName("ChannelName")
	public val channelName: String? = null,
	@SerialName("ChannelPrimaryImageTag")
	public val channelPrimaryImageTag: String? = null,
	/**
	 * Gets or sets the program identifier.
	 */
	@SerialName("ProgramId")
	public val programId: String? = null,
	/**
	 * Gets or sets the external program identifier.
	 */
	@SerialName("ExternalProgramId")
	public val externalProgramId: String? = null,
	/**
	 * Name of the recording.
	 */
	@SerialName("Name")
	public val name: String? = null,
	/**
	 * Description of the recording.
	 */
	@SerialName("Overview")
	public val overview: String? = null,
	/**
	 * The start date of the recording, in UTC.
	 */
	@SerialName("StartDate")
	public val startDate: LocalDateTime,
	/**
	 * The end date of the recording, in UTC.
	 */
	@SerialName("EndDate")
	public val endDate: LocalDateTime,
	/**
	 * Gets or sets the name of the service.
	 */
	@SerialName("ServiceName")
	public val serviceName: String? = null,
	/**
	 * Gets or sets the priority.
	 */
	@SerialName("Priority")
	public val priority: Int,
	/**
	 * Gets or sets the pre padding seconds.
	 */
	@SerialName("PrePaddingSeconds")
	public val prePaddingSeconds: Int,
	/**
	 * Gets or sets the post padding seconds.
	 */
	@SerialName("PostPaddingSeconds")
	public val postPaddingSeconds: Int,
	/**
	 * Gets or sets a value indicating whether this instance is pre padding required.
	 */
	@SerialName("IsPrePaddingRequired")
	public val isPrePaddingRequired: Boolean,
	/**
	 * If the item does not have any backdrops, this will hold the Id of the Parent that has one.
	 */
	@SerialName("ParentBackdropItemId")
	public val parentBackdropItemId: String? = null,
	/**
	 * Gets or sets the parent backdrop image tags.
	 */
	@SerialName("ParentBackdropImageTags")
	public val parentBackdropImageTags: List<String>? = null,
	/**
	 * Gets or sets a value indicating whether this instance is post padding required.
	 */
	@SerialName("IsPostPaddingRequired")
	public val isPostPaddingRequired: Boolean,
	@SerialName("KeepUntil")
	public val keepUntil: KeepUntil,
	/**
	 * Gets or sets the status.
	 */
	@SerialName("Status")
	public val status: RecordingStatus,
	/**
	 * Gets or sets the series timer identifier.
	 */
	@SerialName("SeriesTimerId")
	public val seriesTimerId: String? = null,
	/**
	 * Gets or sets the external series timer identifier.
	 */
	@SerialName("ExternalSeriesTimerId")
	public val externalSeriesTimerId: String? = null,
	/**
	 * Gets or sets the run time ticks.
	 */
	@SerialName("RunTimeTicks")
	public val runTimeTicks: Long? = null,
	/**
	 * Gets or sets the program information.
	 */
	@SerialName("ProgramInfo")
	public val programInfo: BaseItemDto? = null
)
