// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.sdk.model.api.request

import kotlin.Boolean
import kotlin.Deprecated
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * For backwards compatibility parameters can be sent via Query or Body, with Query having higher
 * precedence.
 * Query parameters are obsolete.
 */
@Serializable
public data class GetPostedPlaybackInfoDeprecatedRequest(
	/**
	 * The item id.
	 */
	@SerialName("itemId")
	public val itemId: UUID,
	/**
	 * The user id.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("userId")
	public val userId: UUID? = null,
	/**
	 * The maximum streaming bitrate.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("maxStreamingBitrate")
	public val maxStreamingBitrate: Int? = null,
	/**
	 * The start time in ticks.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("startTimeTicks")
	public val startTimeTicks: Long? = null,
	/**
	 * The audio stream index.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("audioStreamIndex")
	public val audioStreamIndex: Int? = null,
	/**
	 * The subtitle stream index.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("subtitleStreamIndex")
	public val subtitleStreamIndex: Int? = null,
	/**
	 * The maximum number of audio channels.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("maxAudioChannels")
	public val maxAudioChannels: Int? = null,
	/**
	 * The media source id.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("mediaSourceId")
	public val mediaSourceId: String? = null,
	/**
	 * The livestream id.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("liveStreamId")
	public val liveStreamId: String? = null,
	/**
	 * Whether to auto open the livestream.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("autoOpenLiveStream")
	public val autoOpenLiveStream: Boolean? = null,
	/**
	 * Whether to enable direct play. Default: true.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("enableDirectPlay")
	public val enableDirectPlay: Boolean? = null,
	/**
	 * Whether to enable direct stream. Default: true.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("enableDirectStream")
	public val enableDirectStream: Boolean? = null,
	/**
	 * Whether to enable transcoding. Default: true.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("enableTranscoding")
	public val enableTranscoding: Boolean? = null,
	/**
	 * Whether to allow to copy the video stream. Default: true.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("allowVideoStreamCopy")
	public val allowVideoStreamCopy: Boolean? = null,
	/**
	 * Whether to allow to copy the audio stream. Default: true.
	 */
	@Deprecated("This member is deprecated and may be removed in the future")
	@SerialName("allowAudioStreamCopy")
	public val allowAudioStreamCopy: Boolean? = null,
)
