// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.sdk.model.api.request

import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * Opens a media source.
 */
@Serializable
public data class OpenLiveStreamRequest(
	/**
	 * The open token.
	 */
	@SerialName("openToken")
	public val openToken: String? = null,
	/**
	 * The user id.
	 */
	@SerialName("userId")
	public val userId: UUID? = null,
	/**
	 * The play session id.
	 */
	@SerialName("playSessionId")
	public val playSessionId: String? = null,
	/**
	 * The maximum streaming bitrate.
	 */
	@SerialName("maxStreamingBitrate")
	public val maxStreamingBitrate: Int? = null,
	/**
	 * The start time in ticks.
	 */
	@SerialName("startTimeTicks")
	public val startTimeTicks: Long? = null,
	/**
	 * The audio stream index.
	 */
	@SerialName("audioStreamIndex")
	public val audioStreamIndex: Int? = null,
	/**
	 * The subtitle stream index.
	 */
	@SerialName("subtitleStreamIndex")
	public val subtitleStreamIndex: Int? = null,
	/**
	 * The maximum number of audio channels.
	 */
	@SerialName("maxAudioChannels")
	public val maxAudioChannels: Int? = null,
	/**
	 * The item id.
	 */
	@SerialName("itemId")
	public val itemId: UUID? = null,
	/**
	 * Whether to enable direct play. Default: true.
	 */
	@SerialName("enableDirectPlay")
	public val enableDirectPlay: Boolean? = null,
	/**
	 * Whether to enable direct stream. Default: true.
	 */
	@SerialName("enableDirectStream")
	public val enableDirectStream: Boolean? = null,
	/**
	 * Always burn-in subtitle when transcoding.
	 */
	@SerialName("alwaysBurnInSubtitleWhenTranscoding")
	public val alwaysBurnInSubtitleWhenTranscoding: Boolean? = null,
)
