// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.sdk.model.api.request

import kotlin.Boolean
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.api.MetadataRefreshMode
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * Refreshes metadata for an item.
 */
@Serializable
public data class RefreshItemRequest(
	/**
	 * Item id.
	 */
	@SerialName("itemId")
	public val itemId: UUID,
	/**
	 * (Optional) Specifies the metadata refresh mode.
	 */
	@SerialName("metadataRefreshMode")
	public val metadataRefreshMode: MetadataRefreshMode? = MetadataRefreshMode.NONE,
	/**
	 * (Optional) Specifies the image refresh mode.
	 */
	@SerialName("imageRefreshMode")
	public val imageRefreshMode: MetadataRefreshMode? = MetadataRefreshMode.NONE,
	/**
	 * (Optional) Determines if metadata should be replaced. Only applicable if mode is FullRefresh.
	 */
	@SerialName("replaceAllMetadata")
	public val replaceAllMetadata: Boolean? = false,
	/**
	 * (Optional) Determines if images should be replaced. Only applicable if mode is FullRefresh.
	 */
	@SerialName("replaceAllImages")
	public val replaceAllImages: Boolean? = false,
	/**
	 * (Optional) Determines if trickplay images should be replaced. Only applicable if mode is
	 * FullRefresh.
	 */
	@SerialName("regenerateTrickplay")
	public val regenerateTrickplay: Boolean? = false,
)
