// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An enum that represents a day of the week, weekdays, weekends, or all days.
 */
@Serializable
enum class DynamicDayOfWeek {
	@SerialName("Sunday")
	SUNDAY,

	@SerialName("Monday")
	MONDAY,

	@SerialName("Tuesday")
	TUESDAY,

	@SerialName("Wednesday")
	WEDNESDAY,

	@SerialName("Thursday")
	THURSDAY,

	@SerialName("Friday")
	FRIDAY,

	@SerialName("Saturday")
	SATURDAY,

	@SerialName("Everyday")
	EVERYDAY,

	@SerialName("Weekday")
	WEEKDAY,

	@SerialName("Weekend")
	WEEKEND
}
