// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The specific media type of an MediaBrowser.Model.Providers.ExternalIdInfo.
 */
@Serializable
enum class ExternalIdMediaType {
	@SerialName("Album")
	ALBUM,

	@SerialName("AlbumArtist")
	ALBUM_ARTIST,

	@SerialName("Artist")
	ARTIST,

	@SerialName("BoxSet")
	BOX_SET,

	@SerialName("Episode")
	EPISODE,

	@SerialName("Movie")
	MOVIE,

	@SerialName("OtherArtist")
	OTHER_ARTIST,

	@SerialName("Person")
	PERSON,

	@SerialName("ReleaseGroup")
	RELEASE_GROUP,

	@SerialName("Season")
	SEASON,

	@SerialName("Series")
	SERIES,

	@SerialName("Track")
	TRACK
}
