// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(LocalDateTimeSerializer::class)

package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.LocalDateTimeSerializer

@Serializable
data class ForgotPasswordResult(
	@SerialName("Action")
	val action: ForgotPasswordAction? = null,
	/**
	 * Gets or sets the pin file.
	 */
	@SerialName("PinFile")
	val pinFile: String? = null,
	/**
	 * Gets or sets the pin expiration date.
	 */
	@SerialName("PinExpirationDate")
	val pinExpirationDate: LocalDateTime? = null
)
