// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(
	UUIDSerializer::class,
	LocalDateTimeSerializer::class
)

package org.jellyfin.apiclient.model.api

import java.time.LocalDateTime
import java.util.UUID
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.LocalDateTimeSerializer
import org.jellyfin.apiclient.model.serializer.UUIDSerializer

/**
 * Get programs dto.
 */
@Serializable
data class GetProgramsDto(
	/**
	 * Gets or sets the channels to return guide information for.
	 */
	@SerialName("ChannelIds")
	val channelIds: String? = null,
	/**
	 * Gets or sets optional. Filter by user id.
	 */
	@SerialName("UserId")
	val userId: UUID,
	/**
	 * Gets or sets the minimum premiere start date.
	 * Optional.
	 */
	@SerialName("MinStartDate")
	val minStartDate: LocalDateTime? = null,
	/**
	 * Gets or sets filter by programs that have completed airing, or not.
	 * Optional.
	 */
	@SerialName("HasAired")
	val hasAired: Boolean? = null,
	/**
	 * Gets or sets filter by programs that are currently airing, or not.
	 * Optional.
	 */
	@SerialName("IsAiring")
	val isAiring: Boolean? = null,
	/**
	 * Gets or sets the maximum premiere start date.
	 * Optional.
	 */
	@SerialName("MaxStartDate")
	val maxStartDate: LocalDateTime? = null,
	/**
	 * Gets or sets the minimum premiere end date.
	 * Optional.
	 */
	@SerialName("MinEndDate")
	val minEndDate: LocalDateTime? = null,
	/**
	 * Gets or sets the maximum premiere end date.
	 * Optional.
	 */
	@SerialName("MaxEndDate")
	val maxEndDate: LocalDateTime? = null,
	/**
	 * Gets or sets filter for movies.
	 * Optional.
	 */
	@SerialName("IsMovie")
	val isMovie: Boolean? = null,
	/**
	 * Gets or sets filter for series.
	 * Optional.
	 */
	@SerialName("IsSeries")
	val isSeries: Boolean? = null,
	/**
	 * Gets or sets filter for news.
	 * Optional.
	 */
	@SerialName("IsNews")
	val isNews: Boolean? = null,
	/**
	 * Gets or sets filter for kids.
	 * Optional.
	 */
	@SerialName("IsKids")
	val isKids: Boolean? = null,
	/**
	 * Gets or sets filter for sports.
	 * Optional.
	 */
	@SerialName("IsSports")
	val isSports: Boolean? = null,
	/**
	 * Gets or sets the record index to start at. All items with a lower index will be dropped from the
	 * results.
	 * Optional.
	 */
	@SerialName("StartIndex")
	val startIndex: Int? = null,
	/**
	 * Gets or sets the maximum number of records to return.
	 * Optional.
	 */
	@SerialName("Limit")
	val limit: Int? = null,
	/**
	 * Gets or sets specify one or more sort orders, comma delimited. Options: Name, StartDate.
	 * Optional.
	 */
	@SerialName("SortBy")
	val sortBy: String? = null,
	/**
	 * Gets or sets sort Order - Ascending,Descending.
	 */
	@SerialName("SortOrder")
	val sortOrder: String? = null,
	/**
	 * Gets or sets the genres to return guide information for.
	 */
	@SerialName("Genres")
	val genres: String? = null,
	/**
	 * Gets or sets the genre ids to return guide information for.
	 */
	@SerialName("GenreIds")
	val genreIds: String? = null,
	/**
	 * Gets or sets include image information in output.
	 * Optional.
	 */
	@SerialName("EnableImages")
	val enableImages: Boolean? = null,
	/**
	 * Gets or sets a value indicating whether retrieve total record count.
	 */
	@SerialName("EnableTotalRecordCount")
	val enableTotalRecordCount: Boolean,
	/**
	 * Gets or sets the max number of images to return, per image type.
	 * Optional.
	 */
	@SerialName("ImageTypeLimit")
	val imageTypeLimit: Int? = null,
	/**
	 * Gets or sets the image types to include in the output.
	 * Optional.
	 */
	@SerialName("EnableImageTypes")
	val enableImageTypes: String? = null,
	/**
	 * Gets or sets include user data.
	 * Optional.
	 */
	@SerialName("EnableUserData")
	val enableUserData: Boolean? = null,
	/**
	 * Gets or sets filter by series timer id.
	 * Optional.
	 */
	@SerialName("SeriesTimerId")
	val seriesTimerId: String? = null,
	/**
	 * Gets or sets filter by library series id.
	 * Optional.
	 */
	@SerialName("LibrarySeriesId")
	val librarySeriesId: UUID,
	/**
	 * Gets or sets specify additional fields of information to return in the output. This allows
	 * multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl,
	 * IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio,
	 * Revenue, SortName, Studios, Taglines.
	 * Optional.
	 */
	@SerialName("Fields")
	val fields: String? = null
)
