// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlin.Int
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The notification summary DTO.
 */
@Serializable
public data class NotificationsSummaryDto(
	/**
	 * Gets or sets the number of unread notifications.
	 */
	@SerialName("UnreadCount")
	public val unreadCount: Int,
	@SerialName("MaxUnreadNotificationLevel")
	public val maxUnreadNotificationLevel: NotificationLevel? = null
)
