// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.apiclient.model.api

import java.util.UUID
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.UUIDSerializer

/**
 * Class PlayRequest.
 */
@Serializable
public data class PlayRequest(
	/**
	 * Gets or sets the item ids.
	 */
	@SerialName("ItemIds")
	public val itemIds: List<UUID>? = null,
	/**
	 * Gets or sets the start position ticks that the first item should be played at.
	 */
	@SerialName("StartPositionTicks")
	public val startPositionTicks: Long? = null,
	@SerialName("PlayCommand")
	public val playCommand: PlayCommand? = null,
	/**
	 * Gets or sets the controlling user identifier.
	 */
	@SerialName("ControllingUserId")
	public val controllingUserId: UUID,
	@SerialName("SubtitleStreamIndex")
	public val subtitleStreamIndex: Int? = null,
	@SerialName("AudioStreamIndex")
	public val audioStreamIndex: Int? = null,
	@SerialName("MediaSourceId")
	public val mediaSourceId: String? = null,
	@SerialName("StartIndex")
	public val startIndex: Int? = null
)
