// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.apiclient.model.api

import java.util.UUID
import kotlin.Boolean
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.UUIDSerializer

/**
 * Class PlaybackStopInfo.
 */
@Serializable
public data class PlaybackStopInfo(
	@SerialName("Item")
	public val item: BaseItemDto? = null,
	/**
	 * Gets or sets the item identifier.
	 */
	@SerialName("ItemId")
	public val itemId: UUID,
	/**
	 * Gets or sets the session id.
	 */
	@SerialName("SessionId")
	public val sessionId: String? = null,
	/**
	 * Gets or sets the media version identifier.
	 */
	@SerialName("MediaSourceId")
	public val mediaSourceId: String? = null,
	/**
	 * Gets or sets the position ticks.
	 */
	@SerialName("PositionTicks")
	public val positionTicks: Long? = null,
	/**
	 * Gets or sets the live stream identifier.
	 */
	@SerialName("LiveStreamId")
	public val liveStreamId: String? = null,
	/**
	 * Gets or sets the play session identifier.
	 */
	@SerialName("PlaySessionId")
	public val playSessionId: String? = null,
	/**
	 * Gets or sets a value indicating whether this MediaBrowser.Model.Session.PlaybackStopInfo is
	 * failed.
	 */
	@SerialName("Failed")
	public val failed: Boolean,
	@SerialName("NextMediaType")
	public val nextMediaType: String? = null,
	@SerialName("PlaylistItemId")
	public val playlistItemId: String? = null,
	@SerialName("NowPlayingQueue")
	public val nowPlayingQueue: List<QueueItem>? = null
)
