// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Quick connect state.
 */
@Serializable
enum class QuickConnectState {
	@SerialName("Unavailable")
	UNAVAILABLE,

	@SerialName("Available")
	AVAILABLE,

	@SerialName("Active")
	ACTIVE
}
