// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An enum representing a subtitle playback mode.
 */
@Serializable
enum class SubtitlePlaybackMode {
	@SerialName("Default")
	DEFAULT,

	@SerialName("Always")
	ALWAYS,

	@SerialName("OnlyForced")
	ONLY_FORCED,

	@SerialName("None")
	NONE,

	@SerialName("Smart")
	SMART
}
