// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.apiclient.model.api

import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.apiclient.model.serializer.UUIDSerializer

/**
 * Update library options dto.
 */
@Serializable
data class UpdateLibraryOptionsDto(
	/**
	 * Gets or sets the library item id.
	 */
	@SerialName("Id")
	val id: UUID,
	@SerialName("LibraryOptions")
	val libraryOptions: LibraryOptions? = null
)
