// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class Video3dFormat {
	@SerialName("HalfSideBySide")
	HALF_SIDE_BY_SIDE,
	@SerialName("FullSideBySide")
	FULL_SIDE_BY_SIDE,
	@SerialName("FullTopAndBottom")
	FULL_TOP_AND_BOTTOM,
	@SerialName("HalfTopAndBottom")
	HALF_TOP_AND_BOTTOM,
	@SerialName("MVC")
	MVC,
}
