// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.apiclient.model.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enum SendCommandType.
 */
@Serializable
public enum class SendCommandType {
	@SerialName("Unpause")
	UNPAUSE,
	@SerialName("Pause")
	PAUSE,
	@SerialName("Stop")
	STOP,
	@SerialName("Seek")
	SEEK,
}
