// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.api.info

import kotlin.String

public object ApiConstants {
	public const val apiVersion: String = "10.9.0"
}
