name: SDK / Unstable branch

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: unstable-branch

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: master
          token: ${{ secrets.JF_BOT_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Run updateApiSpecUnstable task
        run: ./gradlew :openapi-generator:updateApiSpecUnstable
      - name: Run apiDump task
        run: ./gradlew apiDump
      - name: Commit changes
        if: always()
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git checkout -B openapi-unstable-tmp --no-track origin/master
          git fetch origin openapi-unstable
          git add .
          git commit --allow-empty -m "Update OpenAPI to unstable"
          git diff --quiet origin/openapi-unstable openapi-unstable-tmp || git push --force origin openapi-unstable-tmp:openapi-unstable
